package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m21_annotation_value_2_term table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m21_annotation_value_2_term"
 */
public abstract class BaseTermAnnotationImpl  implements Serializable {

	public static String PROP_ITS_TERM = "ItsTerm";
	public static String PROP_VALUE = "Value";
	public static String PROP_TERMINO_ANNOTATION_TYPE = "TerminoAnnotationType";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _value;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminoAnnotationTypeImpl _terminoAnnotationType;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _itsTerm;


	// constructors
	public BaseTermAnnotationImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTermAnnotationImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: annotation_value
	 */
	public java.lang.String getValue () {
		return _value;
	}

	/**
	 * Set the value related to the column: annotation_value
	 * @param _value the annotation_value value
	 */
	public void setValue (java.lang.String _value) {
		this._value = _value;
	}


	/**
     * @hibernate.property
     *  column=annotation_type_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminoAnnotationTypeImpl getTerminoAnnotationType () {
		return this._terminoAnnotationType;
	}

	/**
	 * Set the value related to the column: annotation_type_id
	 * @param _terminoAnnotationType the annotation_type_id value
	 */
	public void setTerminoAnnotationType (org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminoAnnotationTypeImpl _terminoAnnotationType) {
		this._terminoAnnotationType = _terminoAnnotationType;
	}


	/**
     * @hibernate.property
     *  column=term_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl getItsTerm () {
		return this._itsTerm;
	}

	/**
	 * Set the value related to the column: term_id
	 * @param _itsTerm the term_id value
	 */
	public void setItsTerm (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _itsTerm) {
		this._itsTerm = _itsTerm;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermAnnotationImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermAnnotationImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermAnnotationImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}