package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m11_sentence table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m11_sentence"
 */
public abstract class BaseSentenceImpl  implements Serializable {

	public static String PROP_DOCUMENT = "Document";
	public static String PROP_ORDER_NUMBER = "OrderNumber";
	public static String PROP_ID = "Id";
	public static String PROP_CONTENT = "Content";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _content;
	private java.lang.Integer _orderNumber;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.DocumentImpl _document;

	// collections
	private java.util.Set _termOccurrences;
	private java.util.Set _originRelations;


	// constructors
	public BaseSentenceImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseSentenceImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: content
	 */
	public java.lang.String getContent () {
		return _content;
	}

	/**
	 * Set the value related to the column: content
	 * @param _content the content value
	 */
	public void setContent (java.lang.String _content) {
		this._content = _content;
	}


	/**
	 * Return the value associated with the column: num_order
	 */
	public java.lang.Integer getOrderNumber () {
		return _orderNumber;
	}

	/**
	 * Set the value related to the column: num_order
	 * @param _orderNumber the num_order value
	 */
	public void setOrderNumber (java.lang.Integer _orderNumber) {
		this._orderNumber = _orderNumber;
	}


	/**
     * @hibernate.property
     *  column=doc_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.DocumentImpl getDocument () {
		return this._document;
	}

	/**
	 * Set the value related to the column: doc_id
	 * @param _document the doc_id value
	 */
	public void setDocument (org.dafoe.framework.provider.hibernate.terminological.model.impl.DocumentImpl _document) {
		this._document = _document;
	}


	/**
	 * Return the value associated with the column: TermOccurrences
	 */
	public java.util.Set getTermOccurrences () {
		return this._termOccurrences;
	}

	/**
	 * Set the value related to the column: TermOccurrences
	 * @param _termOccurrences the TermOccurrences value
	 */
	public void setTermOccurrences (java.util.Set _termOccurrences) {
		this._termOccurrences = _termOccurrences;
	}
	
	public void addToTermOccurrences (Object obj) {
		if (null == this._termOccurrences) this._termOccurrences = new java.util.HashSet();
		this._termOccurrences.add(obj);
	}



	/**
	 * Return the value associated with the column: OriginRelations
	 */
	public java.util.Set getOriginRelations () {
		return this._originRelations;
	}

	/**
	 * Set the value related to the column: OriginRelations
	 * @param _originRelations the OriginRelations value
	 */
	public void setOriginRelations (java.util.Set _originRelations) {
		this._originRelations = _originRelations;
	}
	
	public void addToOriginRelations (Object obj) {
		if (null == this._originRelations) this._originRelations = new java.util.HashSet();
		this._originRelations.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseSentenceImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseSentenceImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseSentenceImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}