package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m21_term_relation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m21_term_relation"
 */
public abstract class BaseTermRelationImpl  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_TERMINOLOGY = "Terminology";
	public static String PROP_ID = "Id";
	public static String PROP_TYPE_REL = "TypeRel";
	public static String PROP_TERM2 = "Term2";
	public static String PROP_TERM1 = "Term1";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _status;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _term1;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _term2;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TypeRelationTerminoImpl _typeRel;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl _terminology;

	// collections
	private java.util.Set _originRelation;
	private java.util.Set _mappedTerminoConceptRelations;


	// constructors
	public BaseTermRelationImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTermRelationImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=term1_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl getTerm1 () {
		return this._term1;
	}

	/**
	 * Set the value related to the column: term1_id
	 * @param _term1 the term1_id value
	 */
	public void setTerm1 (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _term1) {
		this._term1 = _term1;
	}


	/**
     * @hibernate.property
     *  column=term2_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl getTerm2 () {
		return this._term2;
	}

	/**
	 * Set the value related to the column: term2_id
	 * @param _term2 the term2_id value
	 */
	public void setTerm2 (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _term2) {
		this._term2 = _term2;
	}


	/**
     * @hibernate.property
     *  column=type_rel_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TypeRelationTerminoImpl getTypeRel () {
		return this._typeRel;
	}

	/**
	 * Set the value related to the column: type_rel_id
	 * @param _typeRel the type_rel_id value
	 */
	public void setTypeRel (org.dafoe.framework.provider.hibernate.terminological.model.impl.TypeRelationTerminoImpl _typeRel) {
		this._typeRel = _typeRel;
	}


	/**
     * @hibernate.property
     *  column=terminology_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl getTerminology () {
		return this._terminology;
	}

	/**
	 * Set the value related to the column: terminology_id
	 * @param _terminology the terminology_id value
	 */
	public void setTerminology (org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl _terminology) {
		this._terminology = _terminology;
	}


	/**
	 * Return the value associated with the column: OriginRelation
	 */
	public java.util.Set getOriginRelation () {
		return this._originRelation;
	}

	/**
	 * Set the value related to the column: OriginRelation
	 * @param _originRelation the OriginRelation value
	 */
	public void setOriginRelation (java.util.Set _originRelation) {
		this._originRelation = _originRelation;
	}
	
	public void addToOriginRelation (Object obj) {
		if (null == this._originRelation) this._originRelation = new java.util.HashSet();
		this._originRelation.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoConceptRelations
	 */
	public java.util.Set getMappedTerminoConceptRelations () {
		return this._mappedTerminoConceptRelations;
	}

	/**
	 * Set the value related to the column: MappedTerminoConceptRelations
	 * @param _mappedTerminoConceptRelations the MappedTerminoConceptRelations value
	 */
	public void setMappedTerminoConceptRelations (java.util.Set _mappedTerminoConceptRelations) {
		this._mappedTerminoConceptRelations = _mappedTerminoConceptRelations;
	}
	
	public void addToMappedTerminoConceptRelations (Object obj) {
		if (null == this._mappedTerminoConceptRelations) this._mappedTerminoConceptRelations = new java.util.HashSet();
		this._mappedTerminoConceptRelations.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermRelationImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermRelationImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermRelationImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}