package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m11_document table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m11_document"
 */
public abstract class BaseDocumentImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_RELATED_CORPUS = "RelatedCorpus";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.CorpusImpl _relatedCorpus;

	// collections
	private java.util.Set _sentences;


	// constructors
	public BaseDocumentImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseDocumentImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="doc_id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
     * @hibernate.property
     *  column=corpus_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.CorpusImpl getRelatedCorpus () {
		return this._relatedCorpus;
	}

	/**
	 * Set the value related to the column: corpus_id
	 * @param _relatedCorpus the corpus_id value
	 */
	public void setRelatedCorpus (org.dafoe.framework.provider.hibernate.terminological.model.impl.CorpusImpl _relatedCorpus) {
		this._relatedCorpus = _relatedCorpus;
	}


	/**
	 * Return the value associated with the column: Sentences
	 */
	public java.util.Set getSentences () {
		return this._sentences;
	}

	/**
	 * Set the value related to the column: Sentences
	 * @param _sentences the Sentences value
	 */
	public void setSentences (java.util.Set _sentences) {
		this._sentences = _sentences;
	}
	
	public void addToSentences (Object obj) {
		if (null == this._sentences) this._sentences = new java.util.HashSet();
		this._sentences.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseDocumentImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseDocumentImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseDocumentImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}