package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m21_method table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m21_method"
 */
public abstract class BaseMethodImpl  implements Serializable {

	public static String PROP_TOOL = "Tool";
	public static String PROP_PATTERN = "Pattern";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _pattern;
	private java.lang.String _tool;

	// collections
	private java.util.Set _typeRelation;
	private java.util.Set _originRelations;


	// constructors
	public BaseMethodImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMethodImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: pattern
	 */
	public java.lang.String getPattern () {
		return _pattern;
	}

	/**
	 * Set the value related to the column: pattern
	 * @param _pattern the pattern value
	 */
	public void setPattern (java.lang.String _pattern) {
		this._pattern = _pattern;
	}


	/**
	 * Return the value associated with the column: tool
	 */
	public java.lang.String getTool () {
		return _tool;
	}

	/**
	 * Set the value related to the column: tool
	 * @param _tool the tool value
	 */
	public void setTool (java.lang.String _tool) {
		this._tool = _tool;
	}


	/**
	 * Return the value associated with the column: TypeRelation
	 */
	public java.util.Set getTypeRelation () {
		return this._typeRelation;
	}

	/**
	 * Set the value related to the column: TypeRelation
	 * @param _typeRelation the TypeRelation value
	 */
	public void setTypeRelation (java.util.Set _typeRelation) {
		this._typeRelation = _typeRelation;
	}
	
	public void addToTypeRelation (Object obj) {
		if (null == this._typeRelation) this._typeRelation = new java.util.HashSet();
		this._typeRelation.add(obj);
	}



	/**
	 * Return the value associated with the column: OriginRelations
	 */
	public java.util.Set getOriginRelations () {
		return this._originRelations;
	}

	/**
	 * Set the value related to the column: OriginRelations
	 * @param _originRelations the OriginRelations value
	 */
	public void setOriginRelations (java.util.Set _originRelations) {
		this._originRelations = _originRelations;
	}
	
	public void addToOriginRelations (Object obj) {
		if (null == this._originRelations) this._originRelations = new java.util.HashSet();
		this._originRelations.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseMethodImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseMethodImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseMethodImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}