package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m11_corpus table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m11_corpus"
 */
public abstract class BaseCorpusImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";
	public static String PROP_PROJECT = "Project";
	public static String PROP_LANGUAGE = "Language";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _language;

	// many to one
	private org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl _project;

	// collections
	private java.util.Set _documents;


	// constructors
	public BaseCorpusImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCorpusImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="corpus_id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: language
	 */
	public java.lang.String getLanguage () {
		return _language;
	}

	/**
	 * Set the value related to the column: language
	 * @param _language the language value
	 */
	public void setLanguage (java.lang.String _language) {
		this._language = _language;
	}


	/**
     * @hibernate.property
     *  column=project_id
	 */
	public org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl getProject () {
		return this._project;
	}

	/**
	 * Set the value related to the column: project_id
	 * @param _project the project_id value
	 */
	public void setProject (org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl _project) {
		this._project = _project;
	}


	/**
	 * Return the value associated with the column: Documents
	 */
	public java.util.Set getDocuments () {
		return this._documents;
	}

	/**
	 * Set the value related to the column: Documents
	 * @param _documents the Documents value
	 */
	public void setDocuments (java.util.Set _documents) {
		this._documents = _documents;
	}
	
	public void addToDocuments (Object obj) {
		if (null == this._documents) this._documents = new java.util.HashSet();
		this._documents.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseCorpusImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseCorpusImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseCorpusImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}