package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m21_type_relation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m21_type_relation"
 */
public abstract class BaseTypeRelationTerminoImpl  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_TERMINOLOGY = "Terminology";
	public static String PROP_ID = "Id";
	public static String PROP_LABEL = "Label";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _label;
	private java.lang.Integer _status;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl _terminology;

	// collections
	private java.util.Set _termRelations;
	private java.util.Set _methods;
	private java.util.Set _mappedTcRelationTypes;


	// constructors
	public BaseTypeRelationTerminoImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTypeRelationTerminoImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: label
	 */
	public java.lang.String getLabel () {
		return _label;
	}

	/**
	 * Set the value related to the column: label
	 * @param _label the label value
	 */
	public void setLabel (java.lang.String _label) {
		this._label = _label;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=terminology_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl getTerminology () {
		return this._terminology;
	}

	/**
	 * Set the value related to the column: terminology_id
	 * @param _terminology the terminology_id value
	 */
	public void setTerminology (org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl _terminology) {
		this._terminology = _terminology;
	}


	/**
	 * Return the value associated with the column: TermRelations
	 */
	public java.util.Set getTermRelations () {
		return this._termRelations;
	}

	/**
	 * Set the value related to the column: TermRelations
	 * @param _termRelations the TermRelations value
	 */
	public void setTermRelations (java.util.Set _termRelations) {
		this._termRelations = _termRelations;
	}
	
	public void addToTermRelations (Object obj) {
		if (null == this._termRelations) this._termRelations = new java.util.HashSet();
		this._termRelations.add(obj);
	}



	/**
	 * Return the value associated with the column: Methods
	 */
	public java.util.Set getMethods () {
		return this._methods;
	}

	/**
	 * Set the value related to the column: Methods
	 * @param _methods the Methods value
	 */
	public void setMethods (java.util.Set _methods) {
		this._methods = _methods;
	}
	
	public void addToMethods (Object obj) {
		if (null == this._methods) this._methods = new java.util.HashSet();
		this._methods.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTcRelationTypes
	 */
	public java.util.Set getMappedTcRelationTypes () {
		return this._mappedTcRelationTypes;
	}

	/**
	 * Set the value related to the column: MappedTcRelationTypes
	 * @param _mappedTcRelationTypes the MappedTcRelationTypes value
	 */
	public void setMappedTcRelationTypes (java.util.Set _mappedTcRelationTypes) {
		this._mappedTcRelationTypes = _mappedTcRelationTypes;
	}
	
	public void addToMappedTcRelationTypes (Object obj) {
		if (null == this._mappedTcRelationTypes) this._mappedTcRelationTypes = new java.util.HashSet();
		this._mappedTcRelationTypes.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTypeRelationTerminoImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTypeRelationTerminoImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTypeRelationTerminoImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}