package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m21_origin_relation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m21_origin_relation"
 */
public abstract class BaseOriginRelationImpl  implements Serializable {

	public static String PROP_TERM_RELATION = "TermRelation";
	public static String PROP_METHOD = "Method";
	public static String PROP_SENTENCE = "Sentence";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.SentenceImpl _sentence;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.MethodImpl _method;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermRelationImpl _termRelation;


	// constructors
	public BaseOriginRelationImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseOriginRelationImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=sentence_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.SentenceImpl getSentence () {
		return this._sentence;
	}

	/**
	 * Set the value related to the column: sentence_id
	 * @param _sentence the sentence_id value
	 */
	public void setSentence (org.dafoe.framework.provider.hibernate.terminological.model.impl.SentenceImpl _sentence) {
		this._sentence = _sentence;
	}


	/**
     * @hibernate.property
     *  column=method_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.MethodImpl getMethod () {
		return this._method;
	}

	/**
	 * Set the value related to the column: method_id
	 * @param _method the method_id value
	 */
	public void setMethod (org.dafoe.framework.provider.hibernate.terminological.model.impl.MethodImpl _method) {
		this._method = _method;
	}


	/**
     * @hibernate.property
     *  column=term_rel_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermRelationImpl getTermRelation () {
		return this._termRelation;
	}

	/**
	 * Set the value related to the column: term_rel_id
	 * @param _termRelation the term_rel_id value
	 */
	public void setTermRelation (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermRelationImpl _termRelation) {
		this._termRelation = _termRelation;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseOriginRelationImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseOriginRelationImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseOriginRelationImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}