package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m21_term_relation_syntactic table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m21_term_relation_syntactic"
 */
public abstract class BaseTermSyntacticRelationImpl  implements Serializable {

	public static String PROP_HEAD_TERM = "HeadTerm";
	public static String PROP_STATUS = "Status";
	public static String PROP_TERMINOLOGY = "Terminology";
	public static String PROP_MODIFIER_TERM = "ModifierTerm";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _status;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _modifierTerm;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _headTerm;
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl _terminology;


	// constructors
	public BaseTermSyntacticRelationImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTermSyntacticRelationImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=modifier_term_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl getModifierTerm () {
		return this._modifierTerm;
	}

	/**
	 * Set the value related to the column: modifier_term_id
	 * @param _modifierTerm the modifier_term_id value
	 */
	public void setModifierTerm (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _modifierTerm) {
		this._modifierTerm = _modifierTerm;
	}


	/**
     * @hibernate.property
     *  column=head_term_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl getHeadTerm () {
		return this._headTerm;
	}

	/**
	 * Set the value related to the column: head_term_id
	 * @param _headTerm the head_term_id value
	 */
	public void setHeadTerm (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _headTerm) {
		this._headTerm = _headTerm;
	}


	/**
     * @hibernate.property
     *  column=terminology_id
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl getTerminology () {
		return this._terminology;
	}

	/**
	 * Set the value related to the column: terminology_id
	 * @param _terminology the terminology_id value
	 */
	public void setTerminology (org.dafoe.framework.provider.hibernate.terminological.model.impl.TerminologyImpl _terminology) {
		this._terminology = _terminology;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermSyntacticRelationImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermSyntacticRelationImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermSyntacticRelationImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}