package org.dafoe.framework.provider.hibernate.terminological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m21_term_saillance table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m21_term_saillance"
 */
public abstract class BaseTermSaillanceImpl  implements Serializable {

	public static String PROP_POSITION_WEIGHT = "PositionWeight";
	public static String PROP_MODIFIER_NEIGHBOR_SIZE = "ModifierNeighborSize";
	public static String PROP_NB_VAR = "NbVar";
	public static String PROP_MODIFIER_PRODUCTIVITY = "ModifierProductivity";
	public static String PROP_TYPOGRAPHICAL_WEIGHT = "TypographicalWeight";
	public static String PROP_ID = "Id";
	public static String PROP_HEAD_NEIGHBOR_SIZE = "HeadNeighborSize";
	public static String PROP_TF_IDF = "TfIdf";
	public static String PROP_FREQUENCY = "Frequency";
	public static String PROP_TERM = "Term";
	public static String PROP_HEAD_PRODUCTIVITY = "HeadProductivity";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _frequency;
	private java.lang.Integer _headProductivity;
	private java.lang.Integer _modifierProductivity;
	private java.lang.Integer _tfIdf;
	private java.lang.Integer _nbVar;
	private java.lang.Integer _typographicalWeight;
	private java.lang.Integer _positionWeight;
	private java.lang.Integer _headNeighborSize;
	private java.lang.Integer _modifierNeighborSize;

	// one to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _term;


	// constructors
	public BaseTermSaillanceImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTermSaillanceImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="foreign"
     *  column="term_id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: frequency
	 */
	public java.lang.Integer getFrequency () {
		return _frequency;
	}

	/**
	 * Set the value related to the column: frequency
	 * @param _frequency the frequency value
	 */
	public void setFrequency (java.lang.Integer _frequency) {
		this._frequency = _frequency;
	}


	/**
	 * Return the value associated with the column: prod_t
	 */
	public java.lang.Integer getHeadProductivity () {
		return _headProductivity;
	}

	/**
	 * Set the value related to the column: prod_t
	 * @param _headProductivity the prod_t value
	 */
	public void setHeadProductivity (java.lang.Integer _headProductivity) {
		this._headProductivity = _headProductivity;
	}


	/**
	 * Return the value associated with the column: prod_e
	 */
	public java.lang.Integer getModifierProductivity () {
		return _modifierProductivity;
	}

	/**
	 * Set the value related to the column: prod_e
	 * @param _modifierProductivity the prod_e value
	 */
	public void setModifierProductivity (java.lang.Integer _modifierProductivity) {
		this._modifierProductivity = _modifierProductivity;
	}


	/**
	 * Return the value associated with the column: tfidf
	 */
	public java.lang.Integer getTfIdf () {
		return _tfIdf;
	}

	/**
	 * Set the value related to the column: tfidf
	 * @param _tfIdf the tfidf value
	 */
	public void setTfIdf (java.lang.Integer _tfIdf) {
		this._tfIdf = _tfIdf;
	}


	/**
	 * Return the value associated with the column: nb_var
	 */
	public java.lang.Integer getNbVar () {
		return _nbVar;
	}

	/**
	 * Set the value related to the column: nb_var
	 * @param _nbVar the nb_var value
	 */
	public void setNbVar (java.lang.Integer _nbVar) {
		this._nbVar = _nbVar;
	}


	/**
	 * Return the value associated with the column: typo_weight
	 */
	public java.lang.Integer getTypographicalWeight () {
		return _typographicalWeight;
	}

	/**
	 * Set the value related to the column: typo_weight
	 * @param _typographicalWeight the typo_weight value
	 */
	public void setTypographicalWeight (java.lang.Integer _typographicalWeight) {
		this._typographicalWeight = _typographicalWeight;
	}


	/**
	 * Return the value associated with the column: position_weight
	 */
	public java.lang.Integer getPositionWeight () {
		return _positionWeight;
	}

	/**
	 * Set the value related to the column: position_weight
	 * @param _positionWeight the position_weight value
	 */
	public void setPositionWeight (java.lang.Integer _positionWeight) {
		this._positionWeight = _positionWeight;
	}


	/**
	 * Return the value associated with the column: nb_voisin_t
	 */
	public java.lang.Integer getHeadNeighborSize () {
		return _headNeighborSize;
	}

	/**
	 * Set the value related to the column: nb_voisin_t
	 * @param _headNeighborSize the nb_voisin_t value
	 */
	public void setHeadNeighborSize (java.lang.Integer _headNeighborSize) {
		this._headNeighborSize = _headNeighborSize;
	}


	/**
	 * Return the value associated with the column: nb_voisin_e
	 */
	public java.lang.Integer getModifierNeighborSize () {
		return _modifierNeighborSize;
	}

	/**
	 * Set the value related to the column: nb_voisin_e
	 * @param _modifierNeighborSize the nb_voisin_e value
	 */
	public void setModifierNeighborSize (java.lang.Integer _modifierNeighborSize) {
		this._modifierNeighborSize = _modifierNeighborSize;
	}


	/**
     * @hibernate.property
     *  column=Term
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl getTerm () {
		return this._term;
	}

	/**
	 * Set the value related to the column: Term
	 * @param _term the Term value
	 */
	public void setTerm (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermImpl _term) {
		this._term = _term;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermSaillanceImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermSaillanceImpl mObj = (org.dafoe.framework.provider.hibernate.terminological.model.impl.base.BaseTermSaillanceImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}