package org.dafoe.framework.databasemodeling.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m24_column table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m24_column"
 */
public abstract class BaseColumnImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_SQL_TYPE = "SqlType";
	public static String PROP_ID = "Id";
	public static String PROP_TABLE = "Table";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _sqlType;

	// many to one
	private org.dafoe.framework.databasemodeling.model.impl.TableImpl _table;


	// constructors
	public BaseColumnImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseColumnImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: sql_type
	 */
	public java.lang.String getSqlType () {
		return _sqlType;
	}

	/**
	 * Set the value related to the column: sql_type
	 * @param _sqlType the sql_type value
	 */
	public void setSqlType (java.lang.String _sqlType) {
		this._sqlType = _sqlType;
	}


	/**
     * @hibernate.property
     *  column=table_id
	 */
	public org.dafoe.framework.databasemodeling.model.impl.TableImpl getTable () {
		return this._table;
	}

	/**
	 * Set the value related to the column: table_id
	 * @param _table the table_id value
	 */
	public void setTable (org.dafoe.framework.databasemodeling.model.impl.TableImpl _table) {
		this._table = _table;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.databasemodeling.model.impl.base.BaseColumnImpl)) return false;
		else {
			org.dafoe.framework.databasemodeling.model.impl.base.BaseColumnImpl mObj = (org.dafoe.framework.databasemodeling.model.impl.base.BaseColumnImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}