package org.dafoe.framework.databasemodeling.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m24_table table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m24_table"
 */
public abstract class BaseTableImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_SCHEMA = "Schema";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;

	// many to one
	private org.dafoe.framework.databasemodeling.model.impl.SchemaImpl _schema;

	// collections
	private java.util.Set _columns;
	private java.util.Set _constraints;


	// constructors
	public BaseTableImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTableImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
     * @hibernate.property
     *  column=schema_id
	 */
	public org.dafoe.framework.databasemodeling.model.impl.SchemaImpl getSchema () {
		return this._schema;
	}

	/**
	 * Set the value related to the column: schema_id
	 * @param _schema the schema_id value
	 */
	public void setSchema (org.dafoe.framework.databasemodeling.model.impl.SchemaImpl _schema) {
		this._schema = _schema;
	}


	/**
	 * Return the value associated with the column: Columns
	 */
	public java.util.Set getColumns () {
		return this._columns;
	}

	/**
	 * Set the value related to the column: Columns
	 * @param _columns the Columns value
	 */
	public void setColumns (java.util.Set _columns) {
		this._columns = _columns;
	}
	
	public void addToColumns (Object obj) {
		if (null == this._columns) this._columns = new java.util.HashSet();
		this._columns.add(obj);
	}



	/**
	 * Return the value associated with the column: Constraints
	 */
	public java.util.Set getConstraints () {
		return this._constraints;
	}

	/**
	 * Set the value related to the column: Constraints
	 * @param _constraints the Constraints value
	 */
	public void setConstraints (java.util.Set _constraints) {
		this._constraints = _constraints;
	}
	
	public void addToConstraints (Object obj) {
		if (null == this._constraints) this._constraints = new java.util.HashSet();
		this._constraints.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.databasemodeling.model.impl.base.BaseTableImpl)) return false;
		else {
			org.dafoe.framework.databasemodeling.model.impl.base.BaseTableImpl mObj = (org.dafoe.framework.databasemodeling.model.impl.base.BaseTableImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}