package org.dafoe.framework.databasemodeling.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m24_constraint table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m24_constraint"
 */
public abstract class BaseConstraintImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";
	public static String PROP_EXPRESSION = "Expression";
	public static String PROP_RELATED_TABLE = "RelatedTable";
	public static String PROP_RELATED_COLUMN = "RelatedColumn";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _expression;

	// many to one
	private org.dafoe.framework.databasemodeling.model.impl.TableImpl _relatedTable;
	private org.dafoe.framework.databasemodeling.model.impl.ColumnImpl _relatedColumn;


	// constructors
	public BaseConstraintImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseConstraintImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: expression
	 */
	public java.lang.String getExpression () {
		return _expression;
	}

	/**
	 * Set the value related to the column: expression
	 * @param _expression the expression value
	 */
	public void setExpression (java.lang.String _expression) {
		this._expression = _expression;
	}


	/**
     * @hibernate.property
     *  column=table_id
	 */
	public org.dafoe.framework.databasemodeling.model.impl.TableImpl getRelatedTable () {
		return this._relatedTable;
	}

	/**
	 * Set the value related to the column: table_id
	 * @param _relatedTable the table_id value
	 */
	public void setRelatedTable (org.dafoe.framework.databasemodeling.model.impl.TableImpl _relatedTable) {
		this._relatedTable = _relatedTable;
	}


	/**
     * @hibernate.property
     *  column=column_id
	 */
	public org.dafoe.framework.databasemodeling.model.impl.ColumnImpl getRelatedColumn () {
		return this._relatedColumn;
	}

	/**
	 * Set the value related to the column: column_id
	 * @param _relatedColumn the column_id value
	 */
	public void setRelatedColumn (org.dafoe.framework.databasemodeling.model.impl.ColumnImpl _relatedColumn) {
		this._relatedColumn = _relatedColumn;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.databasemodeling.model.impl.base.BaseConstraintImpl)) return false;
		else {
			org.dafoe.framework.databasemodeling.model.impl.base.BaseConstraintImpl mObj = (org.dafoe.framework.databasemodeling.model.impl.base.BaseConstraintImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}