package org.dafoe.framework.provider.hibernate.workspace.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m0_project table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m0_project"
 */
public abstract class BaseProjectImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_DATE_LAST_UPDATE = "DateLastUpdate";
	public static String PROP_ID = "Id";
	public static String PROP_DATE_CREATION = "DateCreation";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private java.util.Date _dateCreation;
	private java.util.Date _dateLastUpdate;

	// collections
	private java.util.Set _corpus;
	private java.util.Set _terminologies;
	private java.util.Set _terminoOntologies;
	private java.util.Set _ontologies;


	// constructors
	public BaseProjectImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseProjectImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: date_creation
	 */
	public java.util.Date getDateCreation () {
		return _dateCreation;
	}

	/**
	 * Set the value related to the column: date_creation
	 * @param _dateCreation the date_creation value
	 */
	public void setDateCreation (java.util.Date _dateCreation) {
		this._dateCreation = _dateCreation;
	}


	/**
	 * Return the value associated with the column: date_last_update
	 */
	public java.util.Date getDateLastUpdate () {
		return _dateLastUpdate;
	}

	/**
	 * Set the value related to the column: date_last_update
	 * @param _dateLastUpdate the date_last_update value
	 */
	public void setDateLastUpdate (java.util.Date _dateLastUpdate) {
		this._dateLastUpdate = _dateLastUpdate;
	}


	/**
	 * Return the value associated with the column: Corpus
	 */
	public java.util.Set getCorpus () {
		return this._corpus;
	}

	/**
	 * Set the value related to the column: Corpus
	 * @param _corpus the Corpus value
	 */
	public void setCorpus (java.util.Set _corpus) {
		this._corpus = _corpus;
	}
	
	public void addToCorpus (Object obj) {
		if (null == this._corpus) this._corpus = new java.util.HashSet();
		this._corpus.add(obj);
	}



	/**
	 * Return the value associated with the column: Terminologies
	 */
	public java.util.Set getTerminologies () {
		return this._terminologies;
	}

	/**
	 * Set the value related to the column: Terminologies
	 * @param _terminologies the Terminologies value
	 */
	public void setTerminologies (java.util.Set _terminologies) {
		this._terminologies = _terminologies;
	}
	
	public void addToTerminologies (Object obj) {
		if (null == this._terminologies) this._terminologies = new java.util.HashSet();
		this._terminologies.add(obj);
	}



	/**
	 * Return the value associated with the column: TerminoOntologies
	 */
	public java.util.Set getTerminoOntologies () {
		return this._terminoOntologies;
	}

	/**
	 * Set the value related to the column: TerminoOntologies
	 * @param _terminoOntologies the TerminoOntologies value
	 */
	public void setTerminoOntologies (java.util.Set _terminoOntologies) {
		this._terminoOntologies = _terminoOntologies;
	}
	
	public void addToTerminoOntologies (Object obj) {
		if (null == this._terminoOntologies) this._terminoOntologies = new java.util.HashSet();
		this._terminoOntologies.add(obj);
	}



	/**
	 * Return the value associated with the column: Ontologies
	 */
	public java.util.Set getOntologies () {
		return this._ontologies;
	}

	/**
	 * Set the value related to the column: Ontologies
	 * @param _ontologies the Ontologies value
	 */
	public void setOntologies (java.util.Set _ontologies) {
		this._ontologies = _ontologies;
	}
	
	public void addToOntologies (Object obj) {
		if (null == this._ontologies) this._ontologies = new java.util.HashSet();
		this._ontologies.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.workspace.model.impl.base.BaseProjectImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.workspace.model.impl.base.BaseProjectImpl mObj = (org.dafoe.framework.provider.hibernate.workspace.model.impl.base.BaseProjectImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}