package org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m22_terminoconcept table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m22_terminoconcept"
 */
public abstract class BaseTerminoConceptImpl  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_SIMPLE = "Simple";
	public static String PROP_TERMINO_ONTOLOGY = "TerminoOntology";
	public static String PROP_ID = "Id";
	public static String PROP_SIBLING_SIMILARITY = "SiblingSimilarity";
	public static String PROP_LABEL = "Label";
	public static String PROP_PARENT_DIFFERENCE = "ParentDifference";
	public static String PROP_SIBLING_DIFFERENCE = "SiblingDifference";
	public static String PROP_PARENT_SIMILARITY = "ParentSimilarity";
	public static String PROP_DEFINITION = "Definition";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private boolean _simple;
	private java.lang.String _label;
	private java.lang.String _definition;
	private java.lang.String _parentDifference;
	private java.lang.String _parentSimilarity;
	private java.lang.String _siblingDifference;
	private java.lang.String _siblingSimilarity;
	private java.lang.Integer _status;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoOntologyImpl _terminoOntology;

	// collections
	private java.util.Set _annotations;
	private java.util.Set _terminoConceptOccurrences;
	private java.util.Set _terminoProperties;
	private java.util.Set _relationsMember;
	private java.util.Set _children;
	private java.util.Set _parents;
	private java.util.Set _mappedTerms;
	private java.util.Set _mappedClasses;
	private java.util.Set _mappedDatatypeProperties;
	private java.util.Set _mappedObjectProperties;


	// constructors
	public BaseTerminoConceptImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTerminoConceptImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: is_simple
	 */
	public boolean isSimple () {
		return _simple;
	}

	/**
	 * Set the value related to the column: is_simple
	 * @param _simple the is_simple value
	 */
	public void setSimple (boolean _simple) {
		this._simple = _simple;
	}


	/**
	 * Return the value associated with the column: label
	 */
	public java.lang.String getLabel () {
		return _label;
	}

	/**
	 * Set the value related to the column: label
	 * @param _label the label value
	 */
	public void setLabel (java.lang.String _label) {
		this._label = _label;
	}


	/**
	 * Return the value associated with the column: nl_definition
	 */
	public java.lang.String getDefinition () {
		return _definition;
	}

	/**
	 * Set the value related to the column: nl_definition
	 * @param _definition the nl_definition value
	 */
	public void setDefinition (java.lang.String _definition) {
		this._definition = _definition;
	}


	/**
	 * Return the value associated with the column: parent_diff
	 */
	public java.lang.String getParentDifference () {
		return _parentDifference;
	}

	/**
	 * Set the value related to the column: parent_diff
	 * @param _parentDifference the parent_diff value
	 */
	public void setParentDifference (java.lang.String _parentDifference) {
		this._parentDifference = _parentDifference;
	}


	/**
	 * Return the value associated with the column: parent_similar
	 */
	public java.lang.String getParentSimilarity () {
		return _parentSimilarity;
	}

	/**
	 * Set the value related to the column: parent_similar
	 * @param _parentSimilarity the parent_similar value
	 */
	public void setParentSimilarity (java.lang.String _parentSimilarity) {
		this._parentSimilarity = _parentSimilarity;
	}


	/**
	 * Return the value associated with the column: sibling_diff
	 */
	public java.lang.String getSiblingDifference () {
		return _siblingDifference;
	}

	/**
	 * Set the value related to the column: sibling_diff
	 * @param _siblingDifference the sibling_diff value
	 */
	public void setSiblingDifference (java.lang.String _siblingDifference) {
		this._siblingDifference = _siblingDifference;
	}


	/**
	 * Return the value associated with the column: sibling_similar
	 */
	public java.lang.String getSiblingSimilarity () {
		return _siblingSimilarity;
	}

	/**
	 * Set the value related to the column: sibling_similar
	 * @param _siblingSimilarity the sibling_similar value
	 */
	public void setSiblingSimilarity (java.lang.String _siblingSimilarity) {
		this._siblingSimilarity = _siblingSimilarity;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=termino_ontology_id
	 */
	public org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoOntologyImpl getTerminoOntology () {
		return this._terminoOntology;
	}

	/**
	 * Set the value related to the column: termino_ontology_id
	 * @param _terminoOntology the termino_ontology_id value
	 */
	public void setTerminoOntology (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoOntologyImpl _terminoOntology) {
		this._terminoOntology = _terminoOntology;
	}


	/**
	 * Return the value associated with the column: Annotations
	 */
	public java.util.Set getAnnotations () {
		return this._annotations;
	}

	/**
	 * Set the value related to the column: Annotations
	 * @param _annotations the Annotations value
	 */
	public void setAnnotations (java.util.Set _annotations) {
		this._annotations = _annotations;
	}
	
	public void addToAnnotations (Object obj) {
		if (null == this._annotations) this._annotations = new java.util.HashSet();
		this._annotations.add(obj);
	}



	/**
	 * Return the value associated with the column: TerminoConceptOccurrences
	 */
	public java.util.Set getTerminoConceptOccurrences () {
		return this._terminoConceptOccurrences;
	}

	/**
	 * Set the value related to the column: TerminoConceptOccurrences
	 * @param _terminoConceptOccurrences the TerminoConceptOccurrences value
	 */
	public void setTerminoConceptOccurrences (java.util.Set _terminoConceptOccurrences) {
		this._terminoConceptOccurrences = _terminoConceptOccurrences;
	}
	
	public void addToTerminoConceptOccurrences (Object obj) {
		if (null == this._terminoConceptOccurrences) this._terminoConceptOccurrences = new java.util.HashSet();
		this._terminoConceptOccurrences.add(obj);
	}



	/**
	 * Return the value associated with the column: TerminoProperties
	 */
	public java.util.Set getTerminoProperties () {
		return this._terminoProperties;
	}

	/**
	 * Set the value related to the column: TerminoProperties
	 * @param _terminoProperties the TerminoProperties value
	 */
	public void setTerminoProperties (java.util.Set _terminoProperties) {
		this._terminoProperties = _terminoProperties;
	}
	
	public void addToTerminoProperties (Object obj) {
		if (null == this._terminoProperties) this._terminoProperties = new java.util.HashSet();
		this._terminoProperties.add(obj);
	}



	/**
	 * Return the value associated with the column: RelationsMember
	 */
	public java.util.Set getRelationsMember () {
		return this._relationsMember;
	}

	/**
	 * Set the value related to the column: RelationsMember
	 * @param _relationsMember the RelationsMember value
	 */
	public void setRelationsMember (java.util.Set _relationsMember) {
		this._relationsMember = _relationsMember;
	}
	
	public void addToRelationsMember (Object obj) {
		if (null == this._relationsMember) this._relationsMember = new java.util.HashSet();
		this._relationsMember.add(obj);
	}



	/**
	 * Return the value associated with the column: Children
	 */
	public java.util.Set getChildren () {
		return this._children;
	}

	/**
	 * Set the value related to the column: Children
	 * @param _children the Children value
	 */
	public void setChildren (java.util.Set _children) {
		this._children = _children;
	}
	
	public void addToChildren (Object obj) {
		if (null == this._children) this._children = new java.util.HashSet();
		this._children.add(obj);
	}



	/**
	 * Return the value associated with the column: Parents
	 */
	public java.util.Set getParents () {
		return this._parents;
	}

	/**
	 * Set the value related to the column: Parents
	 * @param _parents the Parents value
	 */
	public void setParents (java.util.Set _parents) {
		this._parents = _parents;
	}
	
	public void addToParents (Object obj) {
		if (null == this._parents) this._parents = new java.util.HashSet();
		this._parents.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerms
	 */
	public java.util.Set getMappedTerms () {
		return this._mappedTerms;
	}

	/**
	 * Set the value related to the column: MappedTerms
	 * @param _mappedTerms the MappedTerms value
	 */
	public void setMappedTerms (java.util.Set _mappedTerms) {
		this._mappedTerms = _mappedTerms;
	}
	
	public void addToMappedTerms (Object obj) {
		if (null == this._mappedTerms) this._mappedTerms = new java.util.HashSet();
		this._mappedTerms.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedClasses
	 */
	public java.util.Set getMappedClasses () {
		return this._mappedClasses;
	}

	/**
	 * Set the value related to the column: MappedClasses
	 * @param _mappedClasses the MappedClasses value
	 */
	public void setMappedClasses (java.util.Set _mappedClasses) {
		this._mappedClasses = _mappedClasses;
	}
	
	public void addToMappedClasses (Object obj) {
		if (null == this._mappedClasses) this._mappedClasses = new java.util.HashSet();
		this._mappedClasses.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedDatatypeProperties
	 */
	public java.util.Set getMappedDatatypeProperties () {
		return this._mappedDatatypeProperties;
	}

	/**
	 * Set the value related to the column: MappedDatatypeProperties
	 * @param _mappedDatatypeProperties the MappedDatatypeProperties value
	 */
	public void setMappedDatatypeProperties (java.util.Set _mappedDatatypeProperties) {
		this._mappedDatatypeProperties = _mappedDatatypeProperties;
	}
	
	public void addToMappedDatatypeProperties (Object obj) {
		if (null == this._mappedDatatypeProperties) this._mappedDatatypeProperties = new java.util.HashSet();
		this._mappedDatatypeProperties.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedObjectProperties
	 */
	public java.util.Set getMappedObjectProperties () {
		return this._mappedObjectProperties;
	}

	/**
	 * Set the value related to the column: MappedObjectProperties
	 * @param _mappedObjectProperties the MappedObjectProperties value
	 */
	public void setMappedObjectProperties (java.util.Set _mappedObjectProperties) {
		this._mappedObjectProperties = _mappedObjectProperties;
	}
	
	public void addToMappedObjectProperties (Object obj) {
		if (null == this._mappedObjectProperties) this._mappedObjectProperties = new java.util.HashSet();
		this._mappedObjectProperties.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptImpl mObj = (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}