package org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m12_terminoconceptoccurrence table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m12_terminoconceptoccurrence"
 */
public abstract class BaseTerminoConceptOccurrenceImpl  implements Serializable {

	public static String PROP_TERMINO_CONCEPT = "TerminoConcept";
	public static String PROP_RELATED_TERM_OCCURENCE = "RelatedTermOccurence";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// one to one
	private org.dafoe.framework.provider.hibernate.terminological.model.impl.TermOccurrenceImpl _relatedTermOccurence;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoConceptImpl _terminoConcept;


	// constructors
	public BaseTerminoConceptOccurrenceImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTerminoConceptOccurrenceImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="foreign"
     *  column="termoccur_id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=RelatedTermOccurence
	 */
	public org.dafoe.framework.provider.hibernate.terminological.model.impl.TermOccurrenceImpl getRelatedTermOccurence () {
		return this._relatedTermOccurence;
	}

	/**
	 * Set the value related to the column: RelatedTermOccurence
	 * @param _relatedTermOccurence the RelatedTermOccurence value
	 */
	public void setRelatedTermOccurence (org.dafoe.framework.provider.hibernate.terminological.model.impl.TermOccurrenceImpl _relatedTermOccurence) {
		this._relatedTermOccurence = _relatedTermOccurence;
	}


	/**
     * @hibernate.property
     *  column=terminoconcept_id
	 */
	public org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoConceptImpl getTerminoConcept () {
		return this._terminoConcept;
	}

	/**
	 * Set the value related to the column: terminoconcept_id
	 * @param _terminoConcept the terminoconcept_id value
	 */
	public void setTerminoConcept (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoConceptImpl _terminoConcept) {
		this._terminoConcept = _terminoConcept;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptOccurrenceImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptOccurrenceImpl mObj = (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptOccurrenceImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}