package org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m22_annotation_value_2_tc table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m22_annotation_value_2_tc"
 */
public abstract class BaseTerminoConceptAnnotationImpl  implements Serializable {

	public static String PROP_VALUE = "Value";
	public static String PROP_TERMINO_ONTO_ANNOTATION_TYPE = "TerminoOntoAnnotationType";
	public static String PROP_ID = "Id";
	public static String PROP_ITS_TERMINO_CONCEPT = "ItsTerminoConcept";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _value;

	// many to one
	private org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoOntoAnnotationTypeImpl _terminoOntoAnnotationType;
	private org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoConceptImpl _itsTerminoConcept;


	// constructors
	public BaseTerminoConceptAnnotationImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTerminoConceptAnnotationImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: annotation_value
	 */
	public java.lang.String getValue () {
		return _value;
	}

	/**
	 * Set the value related to the column: annotation_value
	 * @param _value the annotation_value value
	 */
	public void setValue (java.lang.String _value) {
		this._value = _value;
	}


	/**
     * @hibernate.property
     *  column=annotation_type_id
	 */
	public org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoOntoAnnotationTypeImpl getTerminoOntoAnnotationType () {
		return this._terminoOntoAnnotationType;
	}

	/**
	 * Set the value related to the column: annotation_type_id
	 * @param _terminoOntoAnnotationType the annotation_type_id value
	 */
	public void setTerminoOntoAnnotationType (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoOntoAnnotationTypeImpl _terminoOntoAnnotationType) {
		this._terminoOntoAnnotationType = _terminoOntoAnnotationType;
	}


	/**
     * @hibernate.property
     *  column=tc_id
	 */
	public org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoConceptImpl getItsTerminoConcept () {
		return this._itsTerminoConcept;
	}

	/**
	 * Set the value related to the column: tc_id
	 * @param _itsTerminoConcept the tc_id value
	 */
	public void setItsTerminoConcept (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.TerminoConceptImpl _itsTerminoConcept) {
		this._itsTerminoConcept = _itsTerminoConcept;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptAnnotationImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptAnnotationImpl mObj = (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoConceptAnnotationImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}