package org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m22_terminoontology table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m22_terminoontology"
 */
public abstract class BaseTerminoOntologyImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";
	public static String PROP_PROJECT = "Project";
	public static String PROP_LANGUAGE = "Language";
	public static String PROP_NAME_SPACE = "NameSpace";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _nameSpace;
	private java.lang.String _language;

	// many to one
	private org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl _project;

	// collections
	private java.util.Set _terminoConcepts;
	private java.util.Set _terminoConceptRelations;
	private java.util.Set _typeRelationTcs;
	private java.util.Set _tcSets;
	private java.util.Set _tcLists;
	private java.util.Set _mappedTerminologies;
	private java.util.Set _mappedOntologies;


	// constructors
	public BaseTerminoOntologyImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTerminoOntologyImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: namespace
	 */
	public java.lang.String getNameSpace () {
		return _nameSpace;
	}

	/**
	 * Set the value related to the column: namespace
	 * @param _nameSpace the namespace value
	 */
	public void setNameSpace (java.lang.String _nameSpace) {
		this._nameSpace = _nameSpace;
	}


	/**
	 * Return the value associated with the column: language
	 */
	public java.lang.String getLanguage () {
		return _language;
	}

	/**
	 * Set the value related to the column: language
	 * @param _language the language value
	 */
	public void setLanguage (java.lang.String _language) {
		this._language = _language;
	}


	/**
     * @hibernate.property
     *  column=project_id
	 */
	public org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl getProject () {
		return this._project;
	}

	/**
	 * Set the value related to the column: project_id
	 * @param _project the project_id value
	 */
	public void setProject (org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl _project) {
		this._project = _project;
	}


	/**
	 * Return the value associated with the column: TerminoConcepts
	 */
	public java.util.Set getTerminoConcepts () {
		return this._terminoConcepts;
	}

	/**
	 * Set the value related to the column: TerminoConcepts
	 * @param _terminoConcepts the TerminoConcepts value
	 */
	public void setTerminoConcepts (java.util.Set _terminoConcepts) {
		this._terminoConcepts = _terminoConcepts;
	}
	
	public void addToTerminoConcepts (Object obj) {
		if (null == this._terminoConcepts) this._terminoConcepts = new java.util.HashSet();
		this._terminoConcepts.add(obj);
	}



	/**
	 * Return the value associated with the column: TerminoConceptRelations
	 */
	public java.util.Set getTerminoConceptRelations () {
		return this._terminoConceptRelations;
	}

	/**
	 * Set the value related to the column: TerminoConceptRelations
	 * @param _terminoConceptRelations the TerminoConceptRelations value
	 */
	public void setTerminoConceptRelations (java.util.Set _terminoConceptRelations) {
		this._terminoConceptRelations = _terminoConceptRelations;
	}
	
	public void addToTerminoConceptRelations (Object obj) {
		if (null == this._terminoConceptRelations) this._terminoConceptRelations = new java.util.HashSet();
		this._terminoConceptRelations.add(obj);
	}



	/**
	 * Return the value associated with the column: TypeRelationTcs
	 */
	public java.util.Set getTypeRelationTcs () {
		return this._typeRelationTcs;
	}

	/**
	 * Set the value related to the column: TypeRelationTcs
	 * @param _typeRelationTcs the TypeRelationTcs value
	 */
	public void setTypeRelationTcs (java.util.Set _typeRelationTcs) {
		this._typeRelationTcs = _typeRelationTcs;
	}
	
	public void addToTypeRelationTcs (Object obj) {
		if (null == this._typeRelationTcs) this._typeRelationTcs = new java.util.HashSet();
		this._typeRelationTcs.add(obj);
	}



	/**
	 * Return the value associated with the column: TcSets
	 */
	public java.util.Set getTcSets () {
		return this._tcSets;
	}

	/**
	 * Set the value related to the column: TcSets
	 * @param _tcSets the TcSets value
	 */
	public void setTcSets (java.util.Set _tcSets) {
		this._tcSets = _tcSets;
	}
	
	public void addToTcSets (Object obj) {
		if (null == this._tcSets) this._tcSets = new java.util.HashSet();
		this._tcSets.add(obj);
	}



	/**
	 * Return the value associated with the column: TcLists
	 */
	public java.util.Set getTcLists () {
		return this._tcLists;
	}

	/**
	 * Set the value related to the column: TcLists
	 * @param _tcLists the TcLists value
	 */
	public void setTcLists (java.util.Set _tcLists) {
		this._tcLists = _tcLists;
	}
	
	public void addToTcLists (Object obj) {
		if (null == this._tcLists) this._tcLists = new java.util.HashSet();
		this._tcLists.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminologies
	 */
	public java.util.Set getMappedTerminologies () {
		return this._mappedTerminologies;
	}

	/**
	 * Set the value related to the column: MappedTerminologies
	 * @param _mappedTerminologies the MappedTerminologies value
	 */
	public void setMappedTerminologies (java.util.Set _mappedTerminologies) {
		this._mappedTerminologies = _mappedTerminologies;
	}
	
	public void addToMappedTerminologies (Object obj) {
		if (null == this._mappedTerminologies) this._mappedTerminologies = new java.util.HashSet();
		this._mappedTerminologies.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedOntologies
	 */
	public java.util.Set getMappedOntologies () {
		return this._mappedOntologies;
	}

	/**
	 * Set the value related to the column: MappedOntologies
	 * @param _mappedOntologies the MappedOntologies value
	 */
	public void setMappedOntologies (java.util.Set _mappedOntologies) {
		this._mappedOntologies = _mappedOntologies;
	}
	
	public void addToMappedOntologies (Object obj) {
		if (null == this._mappedOntologies) this._mappedOntologies = new java.util.HashSet();
		this._mappedOntologies.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoOntologyImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoOntologyImpl mObj = (org.dafoe.framework.provider.hibernate.terminoontological.model.impl.base.BaseTerminoOntologyImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}