package org.dafoe.framework.provider.hibernate.ontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m23_annotation_value_2_datatype_prop table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m23_annotation_value_2_datatype_prop"
 */
public abstract class BaseDataTypePropertyAnnotationImpl  implements Serializable {

	public static String PROP_VALUE = "Value";
	public static String PROP_ONTO_ANNOTATION_TYPE = "OntoAnnotationType";
	public static String PROP_ITS_PROPERTY = "ItsProperty";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _value;

	// many to one
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.OntoAnnotationTypeImpl _ontoAnnotationType;
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.DatatypePropertyImpl _itsProperty;


	// constructors
	public BaseDataTypePropertyAnnotationImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseDataTypePropertyAnnotationImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: annotation_value
	 */
	public java.lang.String getValue () {
		return _value;
	}

	/**
	 * Set the value related to the column: annotation_value
	 * @param _value the annotation_value value
	 */
	public void setValue (java.lang.String _value) {
		this._value = _value;
	}


	/**
     * @hibernate.property
     *  column=annotation_type_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.OntoAnnotationTypeImpl getOntoAnnotationType () {
		return this._ontoAnnotationType;
	}

	/**
	 * Set the value related to the column: annotation_type_id
	 * @param _ontoAnnotationType the annotation_type_id value
	 */
	public void setOntoAnnotationType (org.dafoe.framework.provider.hibernate.ontological.model.impl.OntoAnnotationTypeImpl _ontoAnnotationType) {
		this._ontoAnnotationType = _ontoAnnotationType;
	}


	/**
     * @hibernate.property
     *  column=datatype_prop_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.DatatypePropertyImpl getItsProperty () {
		return this._itsProperty;
	}

	/**
	 * Set the value related to the column: datatype_prop_id
	 * @param _itsProperty the datatype_prop_id value
	 */
	public void setItsProperty (org.dafoe.framework.provider.hibernate.ontological.model.impl.DatatypePropertyImpl _itsProperty) {
		this._itsProperty = _itsProperty;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseDataTypePropertyAnnotationImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseDataTypePropertyAnnotationImpl mObj = (org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseDataTypePropertyAnnotationImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}