package org.dafoe.framework.provider.hibernate.ontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m23_datatype_property table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m23_datatype_property"
 */
public abstract class BaseDatatypePropertyImpl  implements Serializable {

	public static String PROP_PARENT = "Parent";
	public static String PROP_STATUS = "Status";
	public static String PROP_RANGE = "Range";
	public static String PROP_ONTOLOGY = "Ontology";
	public static String PROP_MINIMAL_CARDINALITY = "MinimalCardinality";
	public static String PROP_ID = "Id";
	public static String PROP_LABEL = "Label";
	public static String PROP_MAXIMAL_CARDINALITY = "MaximalCardinality";
	public static String PROP_NAME_SPACE = "NameSpace";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _label;
	private java.lang.String _nameSpace;
	private java.lang.Integer _status;
	private java.lang.Integer _maximalCardinality;
	private java.lang.Integer _minimalCardinality;

	// many to one
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.OntologyImpl _ontology;
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.BasicDatatypeImpl _range;
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.DatatypePropertyImpl _parent;

	// collections
	private java.util.Set _domains;
	private java.util.Set _children;
	private java.util.Set _mappedTerminoConceptRelations;
	private java.util.Set _mappedTerminoConcepts;
	private java.util.Set _mappedTerminoConceptRelationTypes;
	private java.util.Set _annotations;
	private java.util.Set _constraintOneOf;
	private java.util.Set _constraintHighThan;
	private java.util.Set _constraintLessThan;
	private java.util.Set _constraintHasValue;
	private java.util.Set _constraintLike;


	// constructors
	public BaseDatatypePropertyImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseDatatypePropertyImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: label
	 */
	public java.lang.String getLabel () {
		return _label;
	}

	/**
	 * Set the value related to the column: label
	 * @param _label the label value
	 */
	public void setLabel (java.lang.String _label) {
		this._label = _label;
	}


	/**
	 * Return the value associated with the column: namespace
	 */
	public java.lang.String getNameSpace () {
		return _nameSpace;
	}

	/**
	 * Set the value related to the column: namespace
	 * @param _nameSpace the namespace value
	 */
	public void setNameSpace (java.lang.String _nameSpace) {
		this._nameSpace = _nameSpace;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: card_max
	 */
	public java.lang.Integer getMaximalCardinality () {
		return _maximalCardinality;
	}

	/**
	 * Set the value related to the column: card_max
	 * @param _maximalCardinality the card_max value
	 */
	public void setMaximalCardinality (java.lang.Integer _maximalCardinality) {
		this._maximalCardinality = _maximalCardinality;
	}


	/**
	 * Return the value associated with the column: card_min
	 */
	public java.lang.Integer getMinimalCardinality () {
		return _minimalCardinality;
	}

	/**
	 * Set the value related to the column: card_min
	 * @param _minimalCardinality the card_min value
	 */
	public void setMinimalCardinality (java.lang.Integer _minimalCardinality) {
		this._minimalCardinality = _minimalCardinality;
	}


	/**
     * @hibernate.property
     *  column=ontology_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.OntologyImpl getOntology () {
		return this._ontology;
	}

	/**
	 * Set the value related to the column: ontology_id
	 * @param _ontology the ontology_id value
	 */
	public void setOntology (org.dafoe.framework.provider.hibernate.ontological.model.impl.OntologyImpl _ontology) {
		this._ontology = _ontology;
	}


	/**
     * @hibernate.property
     *  column=range_basic_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.BasicDatatypeImpl getRange () {
		return this._range;
	}

	/**
	 * Set the value related to the column: range_basic_id
	 * @param _range the range_basic_id value
	 */
	public void setRange (org.dafoe.framework.provider.hibernate.ontological.model.impl.BasicDatatypeImpl _range) {
		this._range = _range;
	}


	/**
     * @hibernate.property
     *  column=parent_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.DatatypePropertyImpl getParent () {
		return this._parent;
	}

	/**
	 * Set the value related to the column: parent_id
	 * @param _parent the parent_id value
	 */
	public void setParent (org.dafoe.framework.provider.hibernate.ontological.model.impl.DatatypePropertyImpl _parent) {
		this._parent = _parent;
	}


	/**
	 * Return the value associated with the column: Domains
	 */
	public java.util.Set getDomains () {
		return this._domains;
	}

	/**
	 * Set the value related to the column: Domains
	 * @param _domains the Domains value
	 */
	public void setDomains (java.util.Set _domains) {
		this._domains = _domains;
	}
	
	public void addToDomains (Object obj) {
		if (null == this._domains) this._domains = new java.util.HashSet();
		this._domains.add(obj);
	}



	/**
	 * Return the value associated with the column: Children
	 */
	public java.util.Set getChildren () {
		return this._children;
	}

	/**
	 * Set the value related to the column: Children
	 * @param _children the Children value
	 */
	public void setChildren (java.util.Set _children) {
		this._children = _children;
	}
	
	public void addToChildren (Object obj) {
		if (null == this._children) this._children = new java.util.HashSet();
		this._children.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoConceptRelations
	 */
	public java.util.Set getMappedTerminoConceptRelations () {
		return this._mappedTerminoConceptRelations;
	}

	/**
	 * Set the value related to the column: MappedTerminoConceptRelations
	 * @param _mappedTerminoConceptRelations the MappedTerminoConceptRelations value
	 */
	public void setMappedTerminoConceptRelations (java.util.Set _mappedTerminoConceptRelations) {
		this._mappedTerminoConceptRelations = _mappedTerminoConceptRelations;
	}
	
	public void addToMappedTerminoConceptRelations (Object obj) {
		if (null == this._mappedTerminoConceptRelations) this._mappedTerminoConceptRelations = new java.util.HashSet();
		this._mappedTerminoConceptRelations.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoConcepts
	 */
	public java.util.Set getMappedTerminoConcepts () {
		return this._mappedTerminoConcepts;
	}

	/**
	 * Set the value related to the column: MappedTerminoConcepts
	 * @param _mappedTerminoConcepts the MappedTerminoConcepts value
	 */
	public void setMappedTerminoConcepts (java.util.Set _mappedTerminoConcepts) {
		this._mappedTerminoConcepts = _mappedTerminoConcepts;
	}
	
	public void addToMappedTerminoConcepts (Object obj) {
		if (null == this._mappedTerminoConcepts) this._mappedTerminoConcepts = new java.util.HashSet();
		this._mappedTerminoConcepts.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoConceptRelationTypes
	 */
	public java.util.Set getMappedTerminoConceptRelationTypes () {
		return this._mappedTerminoConceptRelationTypes;
	}

	/**
	 * Set the value related to the column: MappedTerminoConceptRelationTypes
	 * @param _mappedTerminoConceptRelationTypes the MappedTerminoConceptRelationTypes value
	 */
	public void setMappedTerminoConceptRelationTypes (java.util.Set _mappedTerminoConceptRelationTypes) {
		this._mappedTerminoConceptRelationTypes = _mappedTerminoConceptRelationTypes;
	}
	
	public void addToMappedTerminoConceptRelationTypes (Object obj) {
		if (null == this._mappedTerminoConceptRelationTypes) this._mappedTerminoConceptRelationTypes = new java.util.HashSet();
		this._mappedTerminoConceptRelationTypes.add(obj);
	}



	/**
	 * Return the value associated with the column: Annotations
	 */
	public java.util.Set getAnnotations () {
		return this._annotations;
	}

	/**
	 * Set the value related to the column: Annotations
	 * @param _annotations the Annotations value
	 */
	public void setAnnotations (java.util.Set _annotations) {
		this._annotations = _annotations;
	}
	
	public void addToAnnotations (Object obj) {
		if (null == this._annotations) this._annotations = new java.util.HashSet();
		this._annotations.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintOneOf
	 */
	public java.util.Set getConstraintOneOf () {
		return this._constraintOneOf;
	}

	/**
	 * Set the value related to the column: ConstraintOneOf
	 * @param _constraintOneOf the ConstraintOneOf value
	 */
	public void setConstraintOneOf (java.util.Set _constraintOneOf) {
		this._constraintOneOf = _constraintOneOf;
	}
	
	public void addToConstraintOneOf (Object obj) {
		if (null == this._constraintOneOf) this._constraintOneOf = new java.util.HashSet();
		this._constraintOneOf.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintHighThan
	 */
	public java.util.Set getConstraintHighThan () {
		return this._constraintHighThan;
	}

	/**
	 * Set the value related to the column: ConstraintHighThan
	 * @param _constraintHighThan the ConstraintHighThan value
	 */
	public void setConstraintHighThan (java.util.Set _constraintHighThan) {
		this._constraintHighThan = _constraintHighThan;
	}
	
	public void addToConstraintHighThan (Object obj) {
		if (null == this._constraintHighThan) this._constraintHighThan = new java.util.HashSet();
		this._constraintHighThan.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintLessThan
	 */
	public java.util.Set getConstraintLessThan () {
		return this._constraintLessThan;
	}

	/**
	 * Set the value related to the column: ConstraintLessThan
	 * @param _constraintLessThan the ConstraintLessThan value
	 */
	public void setConstraintLessThan (java.util.Set _constraintLessThan) {
		this._constraintLessThan = _constraintLessThan;
	}
	
	public void addToConstraintLessThan (Object obj) {
		if (null == this._constraintLessThan) this._constraintLessThan = new java.util.HashSet();
		this._constraintLessThan.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintHasValue
	 */
	public java.util.Set getConstraintHasValue () {
		return this._constraintHasValue;
	}

	/**
	 * Set the value related to the column: ConstraintHasValue
	 * @param _constraintHasValue the ConstraintHasValue value
	 */
	public void setConstraintHasValue (java.util.Set _constraintHasValue) {
		this._constraintHasValue = _constraintHasValue;
	}
	
	public void addToConstraintHasValue (Object obj) {
		if (null == this._constraintHasValue) this._constraintHasValue = new java.util.HashSet();
		this._constraintHasValue.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintLike
	 */
	public java.util.Set getConstraintLike () {
		return this._constraintLike;
	}

	/**
	 * Set the value related to the column: ConstraintLike
	 * @param _constraintLike the ConstraintLike value
	 */
	public void setConstraintLike (java.util.Set _constraintLike) {
		this._constraintLike = _constraintLike;
	}
	
	public void addToConstraintLike (Object obj) {
		if (null == this._constraintLike) this._constraintLike = new java.util.HashSet();
		this._constraintLike.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseDatatypePropertyImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseDatatypePropertyImpl mObj = (org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseDatatypePropertyImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}