package org.dafoe.framework.provider.hibernate.ontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m23_ontology table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m23_ontology"
 */
public abstract class BaseOntologyImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";
	public static String PROP_PROJECT = "Project";
	public static String PROP_LANGUAGE = "Language";
	public static String PROP_NAME_SPACE = "NameSpace";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private java.lang.String _nameSpace;
	private java.lang.String _language;

	// many to one
	private org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl _project;

	// collections
	private java.util.Set _classes;
	private java.util.Set _objectProperties;
	private java.util.Set _datatypeProperties;
	private java.util.Set _mappedTerminoOntologies;


	// constructors
	public BaseOntologyImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseOntologyImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="rid"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: namespace
	 */
	public java.lang.String getNameSpace () {
		return _nameSpace;
	}

	/**
	 * Set the value related to the column: namespace
	 * @param _nameSpace the namespace value
	 */
	public void setNameSpace (java.lang.String _nameSpace) {
		this._nameSpace = _nameSpace;
	}


	/**
	 * Return the value associated with the column: language
	 */
	public java.lang.String getLanguage () {
		return _language;
	}

	/**
	 * Set the value related to the column: language
	 * @param _language the language value
	 */
	public void setLanguage (java.lang.String _language) {
		this._language = _language;
	}


	/**
     * @hibernate.property
     *  column=project_id
	 */
	public org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl getProject () {
		return this._project;
	}

	/**
	 * Set the value related to the column: project_id
	 * @param _project the project_id value
	 */
	public void setProject (org.dafoe.framework.provider.hibernate.workspace.model.impl.ProjectImpl _project) {
		this._project = _project;
	}


	/**
	 * Return the value associated with the column: Classes
	 */
	public java.util.Set getClasses () {
		return this._classes;
	}

	/**
	 * Set the value related to the column: Classes
	 * @param _classes the Classes value
	 */
	public void setClasses (java.util.Set _classes) {
		this._classes = _classes;
	}
	
	public void addToClasses (Object obj) {
		if (null == this._classes) this._classes = new java.util.HashSet();
		this._classes.add(obj);
	}



	/**
	 * Return the value associated with the column: ObjectProperties
	 */
	public java.util.Set getObjectProperties () {
		return this._objectProperties;
	}

	/**
	 * Set the value related to the column: ObjectProperties
	 * @param _objectProperties the ObjectProperties value
	 */
	public void setObjectProperties (java.util.Set _objectProperties) {
		this._objectProperties = _objectProperties;
	}
	
	public void addToObjectProperties (Object obj) {
		if (null == this._objectProperties) this._objectProperties = new java.util.HashSet();
		this._objectProperties.add(obj);
	}



	/**
	 * Return the value associated with the column: DatatypeProperties
	 */
	public java.util.Set getDatatypeProperties () {
		return this._datatypeProperties;
	}

	/**
	 * Set the value related to the column: DatatypeProperties
	 * @param _datatypeProperties the DatatypeProperties value
	 */
	public void setDatatypeProperties (java.util.Set _datatypeProperties) {
		this._datatypeProperties = _datatypeProperties;
	}
	
	public void addToDatatypeProperties (Object obj) {
		if (null == this._datatypeProperties) this._datatypeProperties = new java.util.HashSet();
		this._datatypeProperties.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoOntologies
	 */
	public java.util.Set getMappedTerminoOntologies () {
		return this._mappedTerminoOntologies;
	}

	/**
	 * Set the value related to the column: MappedTerminoOntologies
	 * @param _mappedTerminoOntologies the MappedTerminoOntologies value
	 */
	public void setMappedTerminoOntologies (java.util.Set _mappedTerminoOntologies) {
		this._mappedTerminoOntologies = _mappedTerminoOntologies;
	}
	
	public void addToMappedTerminoOntologies (Object obj) {
		if (null == this._mappedTerminoOntologies) this._mappedTerminoOntologies = new java.util.HashSet();
		this._mappedTerminoOntologies.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseOntologyImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseOntologyImpl mObj = (org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseOntologyImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}