package org.dafoe.framework.provider.hibernate.ontological.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m23_object_property table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m23_object_property"
 */
public abstract class BaseObjectPropertyImpl  implements Serializable {

	public static String PROP_PARENT = "Parent";
	public static String PROP_STATUS = "Status";
	public static String PROP_RANGE = "Range";
	public static String PROP_SYMETRIC = "Symetric";
	public static String PROP_ONTOLOGY = "Ontology";
	public static String PROP_INVERSE_OF = "InverseOf";
	public static String PROP_MINIMAL_CARDINALITY = "MinimalCardinality";
	public static String PROP_ID = "Id";
	public static String PROP_LABEL = "Label";
	public static String PROP_MAXIMAL_CARDINALITY = "MaximalCardinality";
	public static String PROP_NAME_SPACE = "NameSpace";
	public static String PROP_TRANSITIVE = "Transitive";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _label;
	private java.lang.String _nameSpace;
	private java.lang.Integer _maximalCardinality;
	private java.lang.Integer _minimalCardinality;
	private boolean _symetric;
	private boolean _transitive;
	private java.lang.Integer _status;

	// many to one
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.OntologyImpl _ontology;
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.ObjectPropertyImpl _inverseOf;
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.ClassImpl _range;
	private org.dafoe.framework.provider.hibernate.ontological.model.impl.ObjectPropertyImpl _parent;

	// collections
	private java.util.Set _domains;
	private java.util.Set _children;
	private java.util.Set _mappedTerminoConceptRelations;
	private java.util.Set _mappedTerminoConcepts;
	private java.util.Set _mappedTerminoConceptRelationTypes;
	private java.util.Set _annotations;
	private java.util.Set _constraintMinMax;
	private java.util.Set _constraintAllValueFrom;
	private java.util.Set _constraintSomeValueFrom;


	// constructors
	public BaseObjectPropertyImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseObjectPropertyImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: label
	 */
	public java.lang.String getLabel () {
		return _label;
	}

	/**
	 * Set the value related to the column: label
	 * @param _label the label value
	 */
	public void setLabel (java.lang.String _label) {
		this._label = _label;
	}


	/**
	 * Return the value associated with the column: namespace
	 */
	public java.lang.String getNameSpace () {
		return _nameSpace;
	}

	/**
	 * Set the value related to the column: namespace
	 * @param _nameSpace the namespace value
	 */
	public void setNameSpace (java.lang.String _nameSpace) {
		this._nameSpace = _nameSpace;
	}


	/**
	 * Return the value associated with the column: card_max
	 */
	public java.lang.Integer getMaximalCardinality () {
		return _maximalCardinality;
	}

	/**
	 * Set the value related to the column: card_max
	 * @param _maximalCardinality the card_max value
	 */
	public void setMaximalCardinality (java.lang.Integer _maximalCardinality) {
		this._maximalCardinality = _maximalCardinality;
	}


	/**
	 * Return the value associated with the column: card_min
	 */
	public java.lang.Integer getMinimalCardinality () {
		return _minimalCardinality;
	}

	/**
	 * Set the value related to the column: card_min
	 * @param _minimalCardinality the card_min value
	 */
	public void setMinimalCardinality (java.lang.Integer _minimalCardinality) {
		this._minimalCardinality = _minimalCardinality;
	}


	/**
	 * Return the value associated with the column: is_symetric
	 */
	public boolean isSymetric () {
		return _symetric;
	}

	/**
	 * Set the value related to the column: is_symetric
	 * @param _symetric the is_symetric value
	 */
	public void setSymetric (boolean _symetric) {
		this._symetric = _symetric;
	}


	/**
	 * Return the value associated with the column: is_transitive
	 */
	public boolean isTransitive () {
		return _transitive;
	}

	/**
	 * Set the value related to the column: is_transitive
	 * @param _transitive the is_transitive value
	 */
	public void setTransitive (boolean _transitive) {
		this._transitive = _transitive;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=ontology_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.OntologyImpl getOntology () {
		return this._ontology;
	}

	/**
	 * Set the value related to the column: ontology_id
	 * @param _ontology the ontology_id value
	 */
	public void setOntology (org.dafoe.framework.provider.hibernate.ontological.model.impl.OntologyImpl _ontology) {
		this._ontology = _ontology;
	}


	/**
     * @hibernate.property
     *  column=inverse_of
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.ObjectPropertyImpl getInverseOf () {
		return this._inverseOf;
	}

	/**
	 * Set the value related to the column: inverse_of
	 * @param _inverseOf the inverse_of value
	 */
	public void setInverseOf (org.dafoe.framework.provider.hibernate.ontological.model.impl.ObjectPropertyImpl _inverseOf) {
		this._inverseOf = _inverseOf;
	}


	/**
     * @hibernate.property
     *  column=range_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.ClassImpl getRange () {
		return this._range;
	}

	/**
	 * Set the value related to the column: range_id
	 * @param _range the range_id value
	 */
	public void setRange (org.dafoe.framework.provider.hibernate.ontological.model.impl.ClassImpl _range) {
		this._range = _range;
	}


	/**
     * @hibernate.property
     *  column=parent_id
	 */
	public org.dafoe.framework.provider.hibernate.ontological.model.impl.ObjectPropertyImpl getParent () {
		return this._parent;
	}

	/**
	 * Set the value related to the column: parent_id
	 * @param _parent the parent_id value
	 */
	public void setParent (org.dafoe.framework.provider.hibernate.ontological.model.impl.ObjectPropertyImpl _parent) {
		this._parent = _parent;
	}


	/**
	 * Return the value associated with the column: Domains
	 */
	public java.util.Set getDomains () {
		return this._domains;
	}

	/**
	 * Set the value related to the column: Domains
	 * @param _domains the Domains value
	 */
	public void setDomains (java.util.Set _domains) {
		this._domains = _domains;
	}
	
	public void addToDomains (Object obj) {
		if (null == this._domains) this._domains = new java.util.HashSet();
		this._domains.add(obj);
	}



	/**
	 * Return the value associated with the column: Children
	 */
	public java.util.Set getChildren () {
		return this._children;
	}

	/**
	 * Set the value related to the column: Children
	 * @param _children the Children value
	 */
	public void setChildren (java.util.Set _children) {
		this._children = _children;
	}
	
	public void addToChildren (Object obj) {
		if (null == this._children) this._children = new java.util.HashSet();
		this._children.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoConceptRelations
	 */
	public java.util.Set getMappedTerminoConceptRelations () {
		return this._mappedTerminoConceptRelations;
	}

	/**
	 * Set the value related to the column: MappedTerminoConceptRelations
	 * @param _mappedTerminoConceptRelations the MappedTerminoConceptRelations value
	 */
	public void setMappedTerminoConceptRelations (java.util.Set _mappedTerminoConceptRelations) {
		this._mappedTerminoConceptRelations = _mappedTerminoConceptRelations;
	}
	
	public void addToMappedTerminoConceptRelations (Object obj) {
		if (null == this._mappedTerminoConceptRelations) this._mappedTerminoConceptRelations = new java.util.HashSet();
		this._mappedTerminoConceptRelations.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoConcepts
	 */
	public java.util.Set getMappedTerminoConcepts () {
		return this._mappedTerminoConcepts;
	}

	/**
	 * Set the value related to the column: MappedTerminoConcepts
	 * @param _mappedTerminoConcepts the MappedTerminoConcepts value
	 */
	public void setMappedTerminoConcepts (java.util.Set _mappedTerminoConcepts) {
		this._mappedTerminoConcepts = _mappedTerminoConcepts;
	}
	
	public void addToMappedTerminoConcepts (Object obj) {
		if (null == this._mappedTerminoConcepts) this._mappedTerminoConcepts = new java.util.HashSet();
		this._mappedTerminoConcepts.add(obj);
	}



	/**
	 * Return the value associated with the column: MappedTerminoConceptRelationTypes
	 */
	public java.util.Set getMappedTerminoConceptRelationTypes () {
		return this._mappedTerminoConceptRelationTypes;
	}

	/**
	 * Set the value related to the column: MappedTerminoConceptRelationTypes
	 * @param _mappedTerminoConceptRelationTypes the MappedTerminoConceptRelationTypes value
	 */
	public void setMappedTerminoConceptRelationTypes (java.util.Set _mappedTerminoConceptRelationTypes) {
		this._mappedTerminoConceptRelationTypes = _mappedTerminoConceptRelationTypes;
	}
	
	public void addToMappedTerminoConceptRelationTypes (Object obj) {
		if (null == this._mappedTerminoConceptRelationTypes) this._mappedTerminoConceptRelationTypes = new java.util.HashSet();
		this._mappedTerminoConceptRelationTypes.add(obj);
	}



	/**
	 * Return the value associated with the column: Annotations
	 */
	public java.util.Set getAnnotations () {
		return this._annotations;
	}

	/**
	 * Set the value related to the column: Annotations
	 * @param _annotations the Annotations value
	 */
	public void setAnnotations (java.util.Set _annotations) {
		this._annotations = _annotations;
	}
	
	public void addToAnnotations (Object obj) {
		if (null == this._annotations) this._annotations = new java.util.HashSet();
		this._annotations.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintMinMax
	 */
	public java.util.Set getConstraintMinMax () {
		return this._constraintMinMax;
	}

	/**
	 * Set the value related to the column: ConstraintMinMax
	 * @param _constraintMinMax the ConstraintMinMax value
	 */
	public void setConstraintMinMax (java.util.Set _constraintMinMax) {
		this._constraintMinMax = _constraintMinMax;
	}
	
	public void addToConstraintMinMax (Object obj) {
		if (null == this._constraintMinMax) this._constraintMinMax = new java.util.HashSet();
		this._constraintMinMax.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintAllValueFrom
	 */
	public java.util.Set getConstraintAllValueFrom () {
		return this._constraintAllValueFrom;
	}

	/**
	 * Set the value related to the column: ConstraintAllValueFrom
	 * @param _constraintAllValueFrom the ConstraintAllValueFrom value
	 */
	public void setConstraintAllValueFrom (java.util.Set _constraintAllValueFrom) {
		this._constraintAllValueFrom = _constraintAllValueFrom;
	}
	
	public void addToConstraintAllValueFrom (Object obj) {
		if (null == this._constraintAllValueFrom) this._constraintAllValueFrom = new java.util.HashSet();
		this._constraintAllValueFrom.add(obj);
	}



	/**
	 * Return the value associated with the column: ConstraintSomeValueFrom
	 */
	public java.util.Set getConstraintSomeValueFrom () {
		return this._constraintSomeValueFrom;
	}

	/**
	 * Set the value related to the column: ConstraintSomeValueFrom
	 * @param _constraintSomeValueFrom the ConstraintSomeValueFrom value
	 */
	public void setConstraintSomeValueFrom (java.util.Set _constraintSomeValueFrom) {
		this._constraintSomeValueFrom = _constraintSomeValueFrom;
	}
	
	public void addToConstraintSomeValueFrom (Object obj) {
		if (null == this._constraintSomeValueFrom) this._constraintSomeValueFrom = new java.util.HashSet();
		this._constraintSomeValueFrom.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseObjectPropertyImpl)) return false;
		else {
			org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseObjectPropertyImpl mObj = (org.dafoe.framework.provider.hibernate.ontological.model.impl.base.BaseObjectPropertyImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}