package org.dafoe.framework.core.metadata.model.impl.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the m3_entity table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="m3_entity"
 */
public abstract class BaseEntityImpl  implements Serializable {

	public static String PROP_NAME = "Name";
	public static String PROP_MODEL = "Model";
	public static String PROP_DYNAMIC = "Dynamic";
	public static String PROP_ID = "Id";
	public static String PROP_RELATED_TABLE = "RelatedTable";
	public static String PROP_ABSTRACT = "Abstract";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.String _name;
	private boolean _abstract;
	private boolean _dynamic;
	private java.lang.String _relatedTable;

	// many to one
	private org.dafoe.framework.core.metadata.model.impl.ModelImpl _model;

	// collections
	private java.util.Set _superEntities;
	private java.util.Set _subEntities;


	// constructors
	public BaseEntityImpl () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseEntityImpl (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="id"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: name
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: name
	 * @param _name the name value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: is_abstract
	 */
	public boolean isAbstract () {
		return _abstract;
	}

	/**
	 * Set the value related to the column: is_abstract
	 * @param _abstract the is_abstract value
	 */
	public void setAbstract (boolean _abstract) {
		this._abstract = _abstract;
	}


	/**
	 * Return the value associated with the column: is_dynamic
	 */
	public boolean isDynamic () {
		return _dynamic;
	}

	/**
	 * Set the value related to the column: is_dynamic
	 * @param _dynamic the is_dynamic value
	 */
	public void setDynamic (boolean _dynamic) {
		this._dynamic = _dynamic;
	}


	/**
	 * Return the value associated with the column: related_table_name
	 */
	public java.lang.String getRelatedTable () {
		return _relatedTable;
	}

	/**
	 * Set the value related to the column: related_table_name
	 * @param _relatedTable the related_table_name value
	 */
	public void setRelatedTable (java.lang.String _relatedTable) {
		this._relatedTable = _relatedTable;
	}


	/**
     * @hibernate.property
     *  column=model_id
	 */
	public org.dafoe.framework.core.metadata.model.impl.ModelImpl getModel () {
		return this._model;
	}

	/**
	 * Set the value related to the column: model_id
	 * @param _model the model_id value
	 */
	public void setModel (org.dafoe.framework.core.metadata.model.impl.ModelImpl _model) {
		this._model = _model;
	}


	/**
	 * Return the value associated with the column: SuperEntities
	 */
	public java.util.Set getSuperEntities () {
		return this._superEntities;
	}

	/**
	 * Set the value related to the column: SuperEntities
	 * @param _superEntities the SuperEntities value
	 */
	public void setSuperEntities (java.util.Set _superEntities) {
		this._superEntities = _superEntities;
	}
	
	public void addToSuperEntities (Object obj) {
		if (null == this._superEntities) this._superEntities = new java.util.HashSet();
		this._superEntities.add(obj);
	}



	/**
	 * Return the value associated with the column: SubEntities
	 */
	public java.util.Set getSubEntities () {
		return this._subEntities;
	}

	/**
	 * Set the value related to the column: SubEntities
	 * @param _subEntities the SubEntities value
	 */
	public void setSubEntities (java.util.Set _subEntities) {
		this._subEntities = _subEntities;
	}
	
	public void addToSubEntities (Object obj) {
		if (null == this._subEntities) this._subEntities = new java.util.HashSet();
		this._subEntities.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.dafoe.framework.core.metadata.model.impl.base.BaseEntityImpl)) return false;
		else {
			org.dafoe.framework.core.metadata.model.impl.base.BaseEntityImpl mObj = (org.dafoe.framework.core.metadata.model.impl.base.BaseEntityImpl) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}